// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: proto/gpt.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GPTRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Temperature   float32 `protobuf:"fixed32,1,opt,name=temperature,proto3" json:"temperature,omitempty"`
	TopP          float32 `protobuf:"fixed32,2,opt,name=top_p,json=topP,proto3" json:"top_p,omitempty"`
	SystemContent string  `protobuf:"bytes,3,opt,name=system_content,json=systemContent,proto3" json:"system_content,omitempty"`
	Prompt        string  `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	RetryTimes    int32   `protobuf:"varint,5,opt,name=retry_times,json=retryTimes,proto3" json:"retry_times,omitempty"`
	IsUse_4       bool    `protobuf:"varint,6,opt,name=is_use_4,json=isUse4,proto3" json:"is_use_4,omitempty"`
	IsFront       bool    `protobuf:"varint,7,opt,name=is_front,json=isFront,proto3" json:"is_front,omitempty"`
}

func (x *GPTRequest) Reset() {
	*x = GPTRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gpt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GPTRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPTRequest) ProtoMessage() {}

func (x *GPTRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPTRequest.ProtoReflect.Descriptor instead.
func (*GPTRequest) Descriptor() ([]byte, []int) {
	return file_proto_gpt_proto_rawDescGZIP(), []int{0}
}

func (x *GPTRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *GPTRequest) GetTopP() float32 {
	if x != nil {
		return x.TopP
	}
	return 0
}

func (x *GPTRequest) GetSystemContent() string {
	if x != nil {
		return x.SystemContent
	}
	return ""
}

func (x *GPTRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GPTRequest) GetRetryTimes() int32 {
	if x != nil {
		return x.RetryTimes
	}
	return 0
}

func (x *GPTRequest) GetIsUse_4() bool {
	if x != nil {
		return x.IsUse_4
	}
	return false
}

func (x *GPTRequest) GetIsFront() bool {
	if x != nil {
		return x.IsFront
	}
	return false
}

type GPTResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg []string `protobuf:"bytes,1,rep,name=msg,proto3" json:"msg,omitempty"`
}

func (x *GPTResponse) Reset() {
	*x = GPTResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gpt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GPTResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPTResponse) ProtoMessage() {}

func (x *GPTResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPTResponse.ProtoReflect.Descriptor instead.
func (*GPTResponse) Descriptor() ([]byte, []int) {
	return file_proto_gpt_proto_rawDescGZIP(), []int{1}
}

func (x *GPTResponse) GetMsg() []string {
	if x != nil {
		return x.Msg
	}
	return nil
}

var File_proto_gpt_proto protoreflect.FileDescriptor

var file_proto_gpt_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x70, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xd8, 0x01, 0x0a, 0x0a, 0x47, 0x50, 0x54, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x20, 0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x5f, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x04, 0x74, 0x6f, 0x70, 0x50, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x74, 0x72, 0x79, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x72, 0x65, 0x74,
	0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x75, 0x73,
	0x65, 0x5f, 0x34, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x55, 0x73, 0x65,
	0x34, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x46, 0x72, 0x6f, 0x6e, 0x74, 0x22, 0x1f, 0x0a, 0x0b,
	0x47, 0x50, 0x54, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0x57, 0x0a,
	0x03, 0x47, 0x50, 0x54, 0x12, 0x2b, 0x0a, 0x0a, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x68,
	0x61, 0x74, 0x12, 0x0b, 0x2e, 0x47, 0x50, 0x54, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0c, 0x2e, 0x47, 0x50, 0x54, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30,
	0x01, 0x12, 0x23, 0x0a, 0x04, 0x43, 0x68, 0x61, 0x74, 0x12, 0x0b, 0x2e, 0x47, 0x50, 0x54, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x47, 0x50, 0x54, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_gpt_proto_rawDescOnce sync.Once
	file_proto_gpt_proto_rawDescData = file_proto_gpt_proto_rawDesc
)

func file_proto_gpt_proto_rawDescGZIP() []byte {
	file_proto_gpt_proto_rawDescOnce.Do(func() {
		file_proto_gpt_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_gpt_proto_rawDescData)
	})
	return file_proto_gpt_proto_rawDescData
}

var file_proto_gpt_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_gpt_proto_goTypes = []interface{}{
	(*GPTRequest)(nil),  // 0: GPTRequest
	(*GPTResponse)(nil), // 1: GPTResponse
}
var file_proto_gpt_proto_depIdxs = []int32{
	0, // 0: GPT.StreamChat:input_type -> GPTRequest
	0, // 1: GPT.Chat:input_type -> GPTRequest
	1, // 2: GPT.StreamChat:output_type -> GPTResponse
	1, // 3: GPT.Chat:output_type -> GPTResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_gpt_proto_init() }
func file_proto_gpt_proto_init() {
	if File_proto_gpt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_gpt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GPTRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gpt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GPTResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_gpt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gpt_proto_goTypes,
		DependencyIndexes: file_proto_gpt_proto_depIdxs,
		MessageInfos:      file_proto_gpt_proto_msgTypes,
	}.Build()
	File_proto_gpt_proto = out.File
	file_proto_gpt_proto_rawDesc = nil
	file_proto_gpt_proto_goTypes = nil
	file_proto_gpt_proto_depIdxs = nil
}
