apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '642'
  creationTimestamp: '2023-03-20T08:01:24Z'
  generation: 644
  labels:
    app: interview
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:app': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:annotations':
                .: {}
                'f:redeploy-timestamp': {}
              'f:labels':
                .: {}
                'f:app': {}
                'f:pod-template-hash': {}
            'f:spec':
              'f:containers':
                'k:{"name":"interview"}':
                  .: {}
                  'f:env':
                    .: {}
                    'k:{"name":"GO_ENV"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"PHONE_DATA_DIR"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"TZ"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"aliyun_logs_interview-dev"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                  'f:image': {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":8040,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:resources':
                    .: {}
                    'f:limits':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                    'f:requests':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
                  'f:volumeMounts':
                    .: {}
                    'k:{"mountPath":"/etc/localtime"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                    'k:{"mountPath":"/root/conf"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
              'f:volumes':
                .: {}
                'k:{"name":"volume-1679299254354"}':
                  .: {}
                  'f:configMap':
                    .: {}
                    'f:defaultMode': {}
                    'f:name': {}
                  'f:name': {}
                'k:{"name":"volume-localtime"}':
                  .: {}
                  'f:hostPath':
                    .: {}
                    'f:path': {}
                    'f:type': {}
                  'f:name': {}
      manager: ACK-Console Apache-HttpClient
      operation: Update
      time: '2024-05-15T08:17:48Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:updatedReplicas': {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: '2024-05-17T03:20:09Z'
  name: interview
  namespace: interview
  resourceVersion: '1961915362'
  uid: 0921a168-b3be-4bd8-a64d-19137ddae5e6
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: interview
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        redeploy-timestamp: '1715916004769'
      labels:
        app: interview
        pod-template-hash: 6b8d8cff7f
    spec:
      containers:
        - env:
            - name: TZ
              value: Asia/Shanghai
            - name: GO_ENV
              value: production
            - name: PHONE_DATA_DIR
              value: /root/
            - name: aliyun_logs_interview-dev
              value: stdout
          image: 'registry-vpc.cn-zhangjiakou.aliyuncs.com/xintujing/interview:v0.2.6'
          imagePullPolicy: Always
          name: interview
          ports:
            - containerPort: 8040
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 513Mi
            requests:
              cpu: 10m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/localtime
              name: volume-localtime
            - mountPath: /root/conf
              name: volume-1679299254354
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ''
          name: volume-localtime
        - configMap:
            defaultMode: 420
            name: interview-cm
          name: volume-1679299254354
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2024-05-06T06:42:06Z'
      lastUpdateTime: '2024-05-06T06:42:06Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2023-05-16T04:01:21Z'
      lastUpdateTime: '2024-05-17T03:20:09Z'
      message: ReplicaSet "interview-6fc9f84cb4" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 644
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
